In [1]:
import numpy as np

<h2>Создание массивов</h2>

In [3]:
# Одномерный
array1 = np.array([1, 2, 3])
array1

[1, 2, 3]

In [5]:
# Двумерный
array2 = np.array([[1, 2, 3], [4, 5, 6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# Массив, рамером 3 на 4, заполненный нулями
array3 = np.zeros([3, 4], dtype=np.int16)
array3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [18]:
# Массив, размерностью 2 на 3 на 4, заполненный единицами
array4 = np.ones([2, 3, 4])
array4

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
array4 = np.ones([2, 3, 4], dtype=np.int64)
array4

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [13]:
# Количество измерений
array4.ndim

3

In [14]:
# Создает пустой массив, в данном случае с двумя элементами
# (значения ненулевые, а приближенные к нулю, зависят от состояния памяти)
np.empty(2)

array([6.23042070e-307, 4.45046008e-307])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Равномерно распределить элементы ОТ заданного числа ДО заданного числа и СКОЛЬКО чисел вывести
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

<h2>Сортировка массива</h2>

In [20]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.random.shuffle(arr)
arr

array([0, 6, 5, 7, 1, 2, 9, 3, 4, 8])

In [24]:
arr = np.sort(arr)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr.argsort()

array([0, 4, 5, 7, 8, 2, 1, 3, 9, 6])

In [28]:
names = np.array(['Alice', 'Bob', 'Alice', 'Bob'])
ages = np.array([25, 30, 20, 25])

np.lexsort((ages, names))

array([2, 0, 3, 1])

<h2>Конкатенация</h2>

In [30]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
c = np.array([[1, 2, 3, 4]])
d = np.array([[4, 5, 6, 7]])
e = np.concatenate([c, d], axis=0)

In [38]:
e.ndim

2

In [39]:
e.size

8

In [40]:
e.shape

(2, 4)

<h3>Добавить измерение</h3>

In [41]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
a[np.newaxis, :]

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [43]:
a[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

<h4>Изменить размерность</h4>

In [46]:
a.reshape(4, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [47]:
a.reshape(8, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

<h4>Срезы</h4>

In [48]:
a[:3]

array([1, 2, 3])

In [50]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [51]:
a[a > 3]

array([4, 5, 6, 7, 8])

In [52]:
a[a != 5]

array([1, 2, 3, 4, 6, 7, 8])

<h3>Действия над массивами</h3>

In [53]:
a1 = np.array([
    [1, 2],
    [3, 4]
])
a2 = np.array([
    [5, 6],
    [7, 8]
])

In [55]:
np.vstack([a1, a2])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [56]:
np.hstack([a1, a2])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [58]:
a1 + a2
np.add(a1, a2)

array([[ 6,  8],
       [10, 12]])

In [59]:
a1 - a2
np.subtract(a1, a2)

array([[-4, -4],
       [-4, -4]])

In [60]:
a1 * a2
np.multiply(a1, a2)

array([[ 5, 12],
       [21, 32]])

In [62]:
a1 / a2
np.divide(a1, a2).round(2)

array([[0.2 , 0.33],
       [0.43, 0.5 ]])

In [64]:
np.sqrt(a1).round(2)

array([[1.  , 1.41],
       [1.73, 2.  ]])

In [66]:
np.exp(a1).round(2)

array([[ 2.72,  7.39],
       [20.09, 54.6 ]])

In [67]:
np.abs(a1)

array([[1, 2],
       [3, 4]])

In [68]:
np.max(a1)

np.int64(4)

In [69]:
np.min(a1)

np.int64(1)

In [71]:
np.log(a1).round(2)

array([[0.  , 0.69],
       [1.1 , 1.39]])

In [72]:
np.mean(a1)

np.float64(2.5)

In [73]:
np.median(a1)

np.float64(2.5)

In [74]:
np.std(a1)

np.float64(1.118033988749895)

In [75]:
np.var(a1)

np.float64(1.25)

<h3>Некоторые другие функции numpy</h3>

In [77]:
# От нуля до одного
np.random.rand(3)

array([0.40021593, 0.53416292, 0.88316245])

In [104]:
m = np.random.rand(3, 3, 4)
m

array([[[0.89353028, 0.88547128, 0.2366899 , 0.85196825],
        [0.52494317, 0.75405253, 0.81809938, 0.82704813],
        [0.90598737, 0.54927904, 0.98128069, 0.45772568]],

       [[0.45353976, 0.57457611, 0.32126295, 0.37800858],
        [0.87834331, 0.46886129, 0.66606594, 0.61751188],
        [0.78714903, 0.91781932, 0.10347234, 0.22666938]],

       [[0.21644728, 0.48623271, 0.62736795, 0.16128007],
        [0.70651307, 0.95130853, 0.20314621, 0.60750573],
        [0.74521806, 0.16658009, 0.3074565 , 0.66926315]]])

In [80]:
np.random.randint(1, 10, size=5)

array([7, 3, 6, 5, 9], dtype=int32)

In [82]:
np.random.randint(3)

2

In [83]:
np.random.randint(1, 10)

3

In [89]:
np.random.choice(a, size=5, replace=False)

array([8, 2, 4, 7, 1])

In [95]:
b = np.array([[1, 2, 3],
              [14, 3, 32],
              [17, 2, 0]])
np.linalg.det(b)

np.float64(955.0000000000001)

In [101]:
inv = np.linalg.inv(b)

In [97]:
a1 = np.array([[1, 2],
              [4, 5]])

a2 = np.array([[4, 5],
               [6, 8]])
np.dot(a1, a2)

array([[16, 21],
       [46, 60]])

In [98]:
a1 @ a2

array([[16, 21],
       [46, 60]])

In [99]:
np.histogram(a)

(array([1, 1, 1, 0, 1, 1, 0, 1, 1, 1]),
 array([1. , 1.7, 2.4, 3.1, 3.8, 4.5, 5.2, 5.9, 6.6, 7.3, 8. ]))

In [100]:
np.corrcoef(a1, a2)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [102]:
inv.T

array([[-0.06701571,  0.56963351, -0.02408377],
       [ 0.00628272, -0.05340314,  0.03350785],
       [ 0.05759162,  0.0104712 , -0.02617801]])

In [106]:
# Создалась из многомерной матрицы одномерная матрица
inv.flatten()

array([-0.06701571,  0.00628272,  0.05759162,  0.56963351, -0.05340314,
        0.0104712 , -0.02408377,  0.03350785, -0.02617801])

In [105]:
m.flatten()

array([0.89353028, 0.88547128, 0.2366899 , 0.85196825, 0.52494317,
       0.75405253, 0.81809938, 0.82704813, 0.90598737, 0.54927904,
       0.98128069, 0.45772568, 0.45353976, 0.57457611, 0.32126295,
       0.37800858, 0.87834331, 0.46886129, 0.66606594, 0.61751188,
       0.78714903, 0.91781932, 0.10347234, 0.22666938, 0.21644728,
       0.48623271, 0.62736795, 0.16128007, 0.70651307, 0.95130853,
       0.20314621, 0.60750573, 0.74521806, 0.16658009, 0.3074565 ,
       0.66926315])

<h3>Broadcasting (транслирование)</h3>

In [115]:
# Если массивы разных размерностей, то к меньшему добавляются новые, чтоб размерности совпали
# Оси с одним элементом расширяются так, чтобы их размерности совпали
# Из старого массива b происходит преобразование в [5, 5, 5, 5, 5, 5, 5, 5]. Это и есть транслирование
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
b = np.array([5])

In [108]:
a + b

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [109]:
a - b

array([-4, -3, -2, -1,  0,  1,  2,  3])

In [111]:
a / b

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6])

In [112]:
c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
d = np.array([1, 2, 3])

In [113]:
c + d

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [114]:
c * d

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])